# Generated by Django 3.2.13 on 2022-04-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=255)),
                ('student_points', models.FloatField()),
                ('math_accetpance', models.BooleanField()),
                ('it_accetpance', models.BooleanField()),
                ('english_accetpance', models.BooleanField()),
                ('italian_acceptance', models.BooleanField()),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
