# Generated by Django 3.2.13 on 2022-05-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='english_accetpance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='it_accetpance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='italian_acceptance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='math_accetpance',
        ),
    ]
